### ISSUE TITLE
Pulling a image with dragonfly is actually slower

### ISSUE THREAD

**Issue by JiaDong007** [dragonflyoss/Dragonfly#1128]
## Question

I am use docker registry,
When using Dragonfly to pull two nodes at the same time:
real	12m39.620s
user	0m2.326s
sys	0m0.892s

When not using Dragonfly to pull two nodes at the same time:
real	6m57.331s
user	0m0.475s
sys	0m0.432s

**Comment by allencloud** [comment]
The statistics you collected is reasonable. Your cluster scale is very small. When your cluster only has 2 nodes, the time is 2 times native pulling times. 

Because the supernode will first download the image from registry. Then node will download image from supernode. Then `real 12m39.620s` is reasonable.

If you have lots of nodes in your cluster, the parallel downloading will consumes all the bandwidth of the registry, then use p2p could save your bandwidth and improve your efficiency. @JiaDong007

**Comment by allencloud** [comment]
I am closing this issue. I am not sure if my answer satisfies you. If you have further questions, please feel free to re-open this issue. Thanks. @JiaDong007

**Comment by JiaDong007** [comment]
Now i have 100 dfclient nodes,but i docker pull the same image in parallel ，them spend more than 20 minutes on average，some cost 1 hour.What is the reason? @allencloud

**Comment by JiaDong007** [comment]
Now i have 100 dfclient nodes,but i docker pull the same image in parallel ，them spend more than 20 minutes on average，some cost 1 hour.What is the reason? @allencloud
