### ISSUE TITLE
Does Dragonfly support pulling singularity container images from the Harbor?

### ISSUE THREAD

**Issue by mohafarooq** [dragonflyoss/Dragonfly#1535]
## Question
Does dfdaemon support pulling singularity images from harbor using oras URI? 

Example:
> singularity pull mytest.sif oras://127.0.0.1:65001/<repo>:<tag>

More details about singularity image pull : https://sylabs.io/guides/3.2/user-guide/cli/singularity_pull.html

**Comment by kt-pham** [comment]
+1

I noticed that in order to get this to go through the tunneling, I had to specify the proxy in front of the singularity command:
HTTPS_PROXY=127.0.0.1:65002 HTTP_PROXY=127.0.0.1:65002 singularity pull oras://registry.com/project/image:tag

However, this does not utilize "dfget" even though I list the registry name underneath the "proxies" section as a regx.

**Comment by mohafarooq** [comment]
Supports.
