### ISSUE TITLE
[linter] dead links exist in markdown documentation

### ISSUE THREAD

**Issue by allencloud** [dragonflyoss/Dragonfly#230]
### Ⅰ. Issue Description

We have enabled markdown-link-check in this repo. And the result shows that the following docs have dead links:

```
FILE: ./CONTRIBUTING.md
[✖] ./.github/ISSUE_TEMPLATE.md

ERROR: dead links found!

FILE: ./docs/faq/_index.md
[✖] docs/en/quick_start.md#use-dragonfly-to-pull-an-image
[✖] docs/en/quick_start.md#use-dragonfly-to-download-a-file

ERROR: dead links found!

FILE: ./docs/overview/what_is_dragonfly.md
[✖] ../../images/performance.png
[✖] ../../images/dfget.png
[✖] ../../images/dfget-combine-container.png
[✖] ../../images/distributing.png

ERROR: dead links found!

FILE: ./apis/README.md
[✖] ../docs/api/api.md

ERROR: dead links found!
```

This is related to https://github.com/alibaba/Dragonfly/pull/229

### Ⅱ. Describe what happened

dead links exist in markdown files.

### Ⅲ. Describe what you expected to happen
 no dead links exist in markdown files.

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1.
2.
3.

### Ⅴ. Anything else we need to know?
none

### Ⅵ. Environment:

- dragonfly version:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by allencloud** [comment]
cc @aliwaredoc 
Please take a look at this? 😄

**Comment by aliwaredoc** [comment]
All dead links except the following ones have been fixed via PR #231 .

FILE: ./docs/overview/what_is_dragonfly.md
[✖] ../../images/performance.png
[✖] ../../images/dfget.png
[✖] ../../images/dfget-combine-container.png
[✖] ../../images/distributing.png

The above dead links are actually working links, because they're relative to the generated static HTML files instead of the raw markdown files. You might want to modify the checking rules.

**Comment by ZYecho** [comment]
cc @allencloud  find another one, in `https://github.com/dragonflyoss/Dragonfly/blob/master/README.md` `Contents` chapter, the `documents` link also missing.

**Comment by allencloud** [comment]
Could you add a pr to fix that? @ZYecho
