### ISSUE TITLE
Wouldn't it be P2P for two dfgets to download files at the same time?

### ISSUE THREAD

**Issue by shuangquan2019** [dragonflyoss/Dragonfly#390]
---
Name: Wouldn't it be P2P for two dfgets to download files at the same time?

// name: 两个dfget同时下载文件不会p2p吗？ 

About: When I was testing, I used two dfget nodes to link supernode to download. I found that both dfget clients directly linked to supernode nodes to download files, and neither side downloaded files from the other side. Is it different from the block download described in the document?

// about: 我在进行测试的时候， 使用了两个dfget 节点链接supernode进行下载， 发现dfget客户端都直接链接supernode节点下载文件， 双方没有相互从对方下载。 好像跟文档描述的分块下载不一样？  

---
## Question
How to let multiple dfget clients download a file at the same time, and download data from other peer nodes. (Tested dfget download will provide PTOP services, download process can not provide services), I am interested in block download. Where are the following files divided? Realize the general principle and process, thank you!

// 怎么样让多个dfget客户端同时下载一个文件的时候，且从其他其他peer节点下载数据， （测试过dfget下载完成会提供ptop服务， 下载过程中不能提供服务）， 我对分块下载感兴趣。 请指导下文件是在哪里分块的？ 实现大概原理和流程， 谢谢！

***!!!!WE STRONGLY ENCOURAGE YOU TO DESCRIBE YOUR ISSUE IN ENGLISH!!!!***

**Comment by fengzixu** [comment]
About this issue, I think that we need some essential info as below:

1. giving us accurate approaches to re-show your question. If you can complete the info about your testing env, that is better.
2. giving us the info of Dragonfly's version so that we can affirm the issue effciently

If you want to know the mechanism about downloading the file piece by piece, you can firstly read the design doc: https://github.com/dragonflyoss/Dragonfly/blob/master/docs/design/design.md

@shuangquan2019

**Comment by Starnop** [comment]
There is no feedback, so close it now.
